[module]

[[module.imports]]
path = "github.com/dnb-hugo/libraries/bootstrap5"
disabled = false

[[module.imports]]
path = "github.com/dnb-hugo/libraries/bootstrap-icons"
disabled = false

[[module.imports]]
path = "github.com/dnb-hugo/blocks/bootstrap5"
disabled = false

[[module.imports]]
path = "github.com/dnb-hugo/shortcodes"
disabled = false

[[module.imports]]
path = "github.com/dnb-hugo/debugprint"
disabled = false

[[module.imports]]
path = "github.com/dnb-hugo/components/functions"
disabled = false

[[module.imports]]
path = "github.com/dnb-hugo/components/robots"
disabled = false

[[module.imports]]
path = "github.com/dnb-hugo/components/search-algolia"
disabled = false

[[module.imports]]
path = "github.com/dnb-hugo/components/sitemap"
disabled = false

[[module.imports]]
path = "github.com/dnb-hugo/components/social"
disabled = false
